### ISSUE TITLE
Can't import tileset

### ISSUE THREAD

**Issue by ghost** [ExplosBlue/CoinKiller#15]
It can export but not import

**Comment by ghost** [comment]
Also Qt Creator keeps having errors compiling it... Can anyone help?

**Comment by Arisotura** [comment]
since Github doesn't support private messaging, I'll ask here: what the hell is that "CoinKiller organization"?

**Comment by iApplepet** [comment]
It's because I can't send a private message sorry. I was wanting to know if you'd be able to tell me how to compile Coinkiller because I've tried Qt creator, Visual Studio, and cmake but none of them work.

**Comment by ghost** [comment]
I've made a bunch of textures and as much of the levels for NSMBU as I can with the old compiled version (I want to try to make NSMBU for the 3DS) but because I can't import any textures (only export them) and edit the other "rooms" I'm kind of stuck.

**Comment by Arisotura** [comment]
and not like you couldn't open an issue (like here) or email me or go to Kuribo64. yeah.

**Comment by iApplepet** [comment]
I forgot about Kirkby 64 and yeah sorry

**Comment by iApplepet** [comment]
Kuribo64

**Comment by iApplepet** [comment]
Is it able to be compiled yet in the first place?

**Comment by ghost** [comment]
I was rushing sorry
