### ISSUE TITLE
No transparency when there are tiles overlapping

### ISSUE THREAD

**Issue by ghost** [ExplosBlue/CoinKiller#16]

**Comment by RicBent** [comment]
wat

**Comment by iApplepet** [comment]
So I make a level (put in my own tiles that behave the same way as the originals= so a texture pack of my own making) but when I play it on my 3DS using romfs patching, all the tiles are scrambled (so instead of a solid floor Mario's standing on a ? block)

**Comment by iApplepet** [comment]
And also the "transparency" of the tiles makes the overlapped tiles transparent as well, making a big transparent gap (this was when I first tried it out too

**Comment by RicBent** [comment]
Not a bug of CoinKiller. You just didn't set the tileset slot.
Also why do you ask this here AND on kuribo64?

Closed.
