### ISSUE TITLE
Suggestion: Make object placement like reggie

### ISSUE THREAD

**Issue by mariomadproductions** [ExplosBlue/CoinKiller#21]
Suggestion: Make object/sprite/whatever placement like reggie
i.e.:

- don't select object when it is placed
- only replace selected objects by clicking on an object from the pallete if "alt" is pressed
- make it so you can change layer of a tileset object by holding "alt" and clicking on "layer 1" or "layer 2" and remove the "change layer up-down" buttons

these would make level editing much easier and more efficient

**Comment by RicBent** [comment]
No, it is intentional.

I have asked a lot people and they mutually agreed that the way NSMBe handels this is way better than Reggie. If you get used to CK you can be a lot quicker.

I might simply add a key combo for switching layers. Alt-pressing on radio buttons is a very ugly solution imo.

**Comment by mariomadproductions** [comment]
...but the "NSMBe method" isn't implemented either.

**Comment by RicBent** [comment]
It is?...

**Comment by mariomadproductions** [comment]
NSMBe has had "don't select object when it is placed" for a while. I suggested it to one of the devs (piranhaplant?) because it made level editing quicker - I got the idea from reggie. :P
