### ISSUE TITLE
Is there a 32 bit version available?

### ISSUE THREAD

**Issue by MidgeThePidge** [ExplosBlue/CoinKiller#32]

**Comment by Luro02** [comment]
I am too lazy to download Qt and compile it so diy ^^
You can try to compile it with this Command:
gcc -m32 main.cpp

(cygwin and qt is needed and maybe some other things that I forgot about O.o)

**Comment by blinkpen** [comment]
are you running windows?

**Comment by RicBent** [comment]
Builds including 32 bit Windows ones can be found here: http://rhcafe.net/board/?page=thread&id=67
