### ISSUE TITLE
Provide a release tarball under releases

### ISSUE THREAD

**Issue by hanaral** [ExplosBlue/CoinKiller#55]
It's a pain in the ass to have to install if you use a GTK based environment. I get that it's under development, but with the amount of GNOME/elementary users there are it would be nice to just have a binary.

**Comment by RicBent** [comment]
The only Linux binaries I can provide would be built on arch which will most likely break for most people.

Building this is as easy as installing QtCreator and hitting run. Shouldn't matter if you use a GTK based environment.

**Comment by ExplosBlue** [comment]
As of 753397258bcdf540afb6d3ef48497302ea614cd7 Linux AppImage binaries are being provided under releases.
