### ISSUE TITLE
Fails to build with -Werror=format-security which means it fails to build in an AUR Package

### ISSUE THREAD

**Issue by furtabs** [ExplosBlue/CoinKiller#61]
https://fedoraproject.org/wiki/Format-Security-FAQ

**Comment by furtabs** [comment]
I cant find a way to disable this flag in the AUR Package

**Comment by ExplosBlue** [comment]
Should build successfully with `-Werror=format-security` as of aa4061176af386fe213f949da3615eca84d16854.
