### ISSUE TITLE
No undo/redo functions

### ISSUE THREAD

**Issue by Treeways** [ExplosBlue/CoinKiller#65]
I'd like to be able to `Ctrl+Z` and `Ctrl+Shift+Z`/`Ctrl+Y`.

Currently, it's possible to simply discard all changes past the previous save by closing the current level, but this would be much more convenient.

**Comment by Treeways** [comment]
This would mainly be for the level editor, but similar functions for the tileset editor would be nice too.

**Comment by ExplosBlue** [comment]
Implemented in fb77b9bd5d846b3c34b1eeebce94e09654f539ee
