### ISSUE TITLE
No pre-compiled version.

### ISSUE THREAD

**Issue by NathanDreamweaver** [ExplosBlue/CoinKiller#9]
There is no pre-compiled version!

**Comment by ant888nsmb2** [comment]
I have this build: http://kuribo64.net/get.php?id=fP984lfUQChOHnsm
Hopefully I helped.

**Comment by Arisotura** [comment]
build it yourself or wait for a release

**Comment by NathanDreamweaver** [comment]
how do i build it? i know how to compile 3ds hoembrews, but how do i compile this?

**Comment by RicBent** [comment]
Use QtCreator
