### ISSUE TITLE
Doesnt work on macos high sierra

### ISSUE THREAD

**Issue by Gustafield** [ExplosBlue/CoinKiller#91]
self explanatory- it wont work on high sierra and my mac is old so it cant update... if theres a reason to why this cant be fixed, is there a way to compile the new coinkiller versions for high sierra?

**Comment by ExplosBlue** [comment]
The version of Qt we use no longer has support for macOS 10, and as such CoinKiller also no longer supports macOS 10.

You may have some success in attempting to compile with an older Qt release that does have support for macOS 10, but this is not something we plan to provide any support for going forward.
